// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOtahlfQgPnJ202dA-KEKrYcShaaGMwFk',
    appId: '1:339960123508:web:e733175e6870ce13c60121',
    messagingSenderId: '339960123508',
    projectId: 'fir-pruebarebeca',
    authDomain: 'fir-pruebarebeca.firebaseapp.com',
    storageBucket: 'fir-pruebarebeca.appspot.com',
    measurementId: 'G-FC2ZT0P82K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAN_5xbvOjMMcIMBPcReLi69GbyZX8I1U',
    appId: '1:339960123508:android:78f265aa45ed19f3c60121',
    messagingSenderId: '339960123508',
    projectId: 'fir-pruebarebeca',
    storageBucket: 'fir-pruebarebeca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgsZe1uETTxfzlE0QpMsXVATbWS01qyxQ',
    appId: '1:339960123508:ios:84c38359de8a30afc60121',
    messagingSenderId: '339960123508',
    projectId: 'fir-pruebarebeca',
    storageBucket: 'fir-pruebarebeca.appspot.com',
    androidClientId: '339960123508-0fe4l8e1mkqkmndis5vk5i8jth7qi632.apps.googleusercontent.com',
    iosClientId: '339960123508-sbmp1fmnl0j3t7q0ol8336o1t1p80jbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgsZe1uETTxfzlE0QpMsXVATbWS01qyxQ',
    appId: '1:339960123508:ios:84c38359de8a30afc60121',
    messagingSenderId: '339960123508',
    projectId: 'fir-pruebarebeca',
    storageBucket: 'fir-pruebarebeca.appspot.com',
    androidClientId: '339960123508-0fe4l8e1mkqkmndis5vk5i8jth7qi632.apps.googleusercontent.com',
    iosClientId: '339960123508-sbmp1fmnl0j3t7q0ol8336o1t1p80jbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
